apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-vite-app-deployment
  namespace: vite-app
  labels:
    app: react-vite-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-vite-app
  template:
    metadata:
      namespace: vite-app
      labels:
        app: react-vite-app
    spec:
      containers:
        - name: react-vite-app-container
          image: randeepgreyghost94/react-vite-devops-app
          ports:
            - containerPort: 5173
