apiVersion: v1
kind: Service
metadata:
  name: react-vite-app-service
  namespace: vite-app
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: react-vite-app
  ports:
    - port: 80
      targetPort: 5173
      nodePort: 30009
